"""Drafting the corpus: allocation, hashed prompts, requests, logging.

Nothing in this package calls a model by itself. A backend is passed in, and
the only backend that can reach a network refuses unless the configuration
enables live calls *and* the caller asks for one explicitly.

The flow is deliberately file-based, so that every request can be read before
it is sent and every response is kept exactly as it arrived:

    allocation  ->  requests (files)  ->  [backend]  ->  responses (files)
                                                     ->  log + corpus records

:mod:`provenance` closes the loop: it rebuilds each request from the curated
brief, the allocation and the hashed template, and checks that the request
which was actually sent matches. That is what makes independence from the
source datasets a procedural guarantee rather than a claim.
"""

from .allocation import (
    AllocationError,
    GroupAllocation,
    MarkerAllocation,
    allocate_markers,
    allocation_problems,
    load_allocation,
    save_allocation,
)
from .approvals import (
    APPROVED,
    ApprovalError,
    ScenarioApproval,
    approval_status,
    gate_problems,
    load_approvals,
    save_approvals,
)
from .assemble import (
    AssemblyError,
    AssemblyRefused,
    ManualCorrection,
    assemble_scenario,
    correction_problems,
    load_corrections,
    save_corrections,
)
from .backends import (
    AUTHORIZATION_ENV,
    BackendError,
    BackendUnavailable,
    FakeBackend,
    LiveCallRefused,
    VLLMOpenAIBackend,
    authorization_problems,
    offline_problems,
    request_payload,
    vllm_payload,
)
from .openai_responses import (
    API_KEY_ENV,
    OPENAI_AUTHORIZATION_ENV,
    OPENAI_BACKEND,
    OpenAIAuthError,
    OpenAIModelUnavailable,
    OpenAIRateLimited,
    OpenAIResponsesBackend,
    openai_authorization_problems,
    openai_preflight_problems,
    openai_responses_payload,
    redact_secrets,
)
from .environment import (
    CachedModel,
    ModelNotCached,
    RunEnvironment,
    describe_run,
    generator_endpoint,
    generator_model_id,
    load_server_runtime,
    missing_weights,
    resolve_cached_model,
    revision_agreement,
    server_settings_problems,
)
from .log import GenerationLog, LogEntry
from .requests import (
    DraftRequest,
    RequestError,
    ResponseRejected,
    group_request,
    parse_response,
    repair_request,
    scenario_request,
    write_request,
)
from .pipeline import (
    ABORTED,
    ACCEPTED,
    Attempt,
    CallStore,
    GROUP_STAGE_AUTHORIZATION_RECORD_VERSION,
    GROUP_STAGE_KIND,
    GroupStageTarget,
    NEEDS_MANUAL_REVIEW,
    PipelineAbort,
    StageResult,
    draft_group,
    draft_scenario,
    group_stage_targets,
    run_initial_group_stage,
    run_pilot,
    transport_blocked_group_targets,
)
from .redraft import (
    STAGE_AUTHORIZATION_RECORD_VERSION,
    RedraftTarget,
    current_scenarios,
    redraft_request,
    redraft_targets,
    redraft_template_sha256,
    run_redraft_stage,
    transport_blocked_targets,
)
from .scenario_corrections import (
    ScenarioCorrection,
    ScenarioCorrectionError,
    apply_scenario_corrections,
    load_scenario_corrections,
    save_scenario_corrections,
)
from .stage_authorization import (
    StageAuthorizationError,
    group_stage_authorization_problems,
    load_stage_authorization,
    stage_authorization_problems,
)
from .provenance import ProvenanceMismatch, check_request_provenance

__all__ = [
    "ABORTED",
    "APPROVED",
    "ApprovalError",
    "AssemblyError",
    "AssemblyRefused",
    "ManualCorrection",
    "ScenarioApproval",
    "ScenarioCorrection",
    "ScenarioCorrectionError",
    "approval_status",
    "apply_scenario_corrections",
    "assemble_scenario",
    "correction_problems",
    "gate_problems",
    "load_approvals",
    "load_corrections",
    "load_scenario_corrections",
    "save_approvals",
    "save_corrections",
    "save_scenario_corrections",
    "ACCEPTED",
    "API_KEY_ENV",
    "AUTHORIZATION_ENV",
    "OPENAI_AUTHORIZATION_ENV",
    "OPENAI_BACKEND",
    "OpenAIAuthError",
    "OpenAIModelUnavailable",
    "OpenAIRateLimited",
    "OpenAIResponsesBackend",
    "openai_authorization_problems",
    "openai_preflight_problems",
    "openai_responses_payload",
    "redact_secrets",
    "request_payload",
    "AllocationError",
    "Attempt",
    "CallStore",
    "NEEDS_MANUAL_REVIEW",
    "PipelineAbort",
    "RedraftTarget",
    "STAGE_AUTHORIZATION_RECORD_VERSION",
    "current_scenarios",
    "redraft_request",
    "redraft_targets",
    "redraft_template_sha256",
    "run_redraft_stage",
    "transport_blocked_targets",
    "StageResult",
    "GROUP_STAGE_AUTHORIZATION_RECORD_VERSION",
    "GROUP_STAGE_KIND",
    "GroupStageTarget",
    "draft_group",
    "draft_scenario",
    "group_stage_targets",
    "run_initial_group_stage",
    "run_pilot",
    "transport_blocked_group_targets",
    "BackendError",
    "BackendUnavailable",
    "CachedModel",
    "DraftRequest",
    "FakeBackend",
    "GenerationLog",
    "GroupAllocation",
    "LiveCallRefused",
    "LogEntry",
    "MarkerAllocation",
    "ModelNotCached",
    "ProvenanceMismatch",
    "RequestError",
    "ResponseRejected",
    "RunEnvironment",
    "VLLMOpenAIBackend",
    "allocate_markers",
    "allocation_problems",
    "authorization_problems",
    "check_request_provenance",
    "describe_run",
    "generator_endpoint",
    "generator_model_id",
    "group_request",
    "load_allocation",
    "load_server_runtime",
    "missing_weights",
    "offline_problems",
    "parse_response",
    "repair_request",
    "resolve_cached_model",
    "revision_agreement",
    "server_settings_problems",
    "save_allocation",
    "scenario_request",
    "vllm_payload",
    "write_request",
    "StageAuthorizationError",
    "group_stage_authorization_problems",
    "load_stage_authorization",
    "stage_authorization_problems",
]
